name: Validate

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '16'

    - name: install dependencies
      run: npm install

    - name: compile TypeScript
      run: npm run build

    - name: run unit tests
      run: npm test

  validate_draft_requests:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft
    steps:
      - name: Validate Draft PR
        run: exit 1

  validate_request_description:
    runs-on: ubuntu-latest
    if: github.event.pull_request.body == ''
    steps:
      - name: Validate PR Description
        run: exit 1